/**
 * Single source of truth for API error codes.
 * These codes are expected to be present in the `code` field of `ApiMessage`
 * when an API response indicates an error.
 */
export const ApiErrorCodes = {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
  AUTH_NO_ACTIVE_SESSION: 'AUTH_NO_ACTIVE_SESSION',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_REGISTER_FAILED: 'AUTH_REGISTER_FAILED',
  AUTH_FORGOT_PASSWORD_FAILED: 'AUTH_FORGOT_PASSWORD_FAILED',
  AUTH_RESET_PASSWORD_FAILED: 'AUTH_RESET_PASSWORD_FAILED',
  AUTH_FIND_ALL_FAILED: 'AUTH_FIND_ALL_FAILED',
  AUTH_FIND_BY_ID_FAILED: 'AUTH_FIND_BY_ID_FAILED',
  AUTH_SAVE_FAILED: 'AUTH_SAVE_FAILED',
  AUTH_DELETE_FAILED: 'AUTH_DELETE_FAILED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Resource related
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  // General Server Errors
  ERR_FR_TOO_MANY_REDIRECTS: 'ERR_FR_TOO_MANY_REDIRECTS',
  ERR_BAD_OPTION_VALUE: 'ERR_BAD_OPTION_VALUE',
  ERR_BAD_OPTION: 'ERR_BAD_OPTION',
  ERR_NETWORK: 'ERR_NETWORK',
  ERR_DEPRECATED: 'ERR_DEPRECATED',
  ERR_BAD_RESPONSE: 'ERR_BAD_RESPONSE',
  ERR_BAD_REQUEST: 'ERR_BAD_REQUEST',
  ERR_NOT_SUPPORT: 'ERR_NOT_SUPPORT',
  ERR_INVALID_URL: 'ERR_INVALID_URL',
  ERR_CANCELED: 'ERR_CANCELED',
  ECONNABORTED: 'ECONNABORTED',
  ETIMEDOUT: 'ETIMEDOUT',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;
