/**
 * Single source of truth for API success codes.
 * These codes are expected to be present in the `code` field of `ApiMessage`
 * when an API response indicates a successful operation with a specific outcome.
 */
export const ApiSuccessCodes = {
  AUTH_LOGIN_SUCCESSFUL: 'AUTH_LOGIN_SUCCESSFUL',
  AUTH_REGISTRATION_SUCCESSFUL: 'AUTH_REGISTRATION_SUCCESSFUL',
  AUTH_LOGOUT_SUCCESSFUL: 'AUTH_LOGOUT_SUCCESSFUL',
  AUTH_REFRESH_TOKEN_SUCCESSFUL: 'AUTH_REFRESH_TOKEN_SUCCESSFUL',
  AUTH_PASSWORD_RESET_SUCCESSFUL: 'AUTH_PASSWORD_RESET_SUCCESSFUL',
  AUTH_PASSWORD_RESET_CONFIRMATION_SUCCESSFUL: 'AUTH_PASSWORD_RESET_CONFIRMATION_SUCCESSFUL',
  AUTH_EMAIL_VERIFICATION_SUCCESSFUL: 'AUTH_EMAIL_VERIFICATION_SUCCESSFUL',
  AUTH_EMAIL_VERIFICATION_CONFIRMATION_SUCCESSFUL:
    'AUTH_EMAIL_VERIFICATION_CONFIRMATION_SUCCESSFUL',
  // Add other success codes as needed
  GENERAL_SUCCESS: 'GENERAL_SUCCESS',
} as const;
