name: acamae-frontend

services:
  frontend:
    build:
      context: ../
    command: ['npm', 'run', 'start:dev']
    container_name: acamae-frontend
    stdin_open: true
    tty: true
    env_file:
      - ../.env.development
    expose:
      - '3000'
    volumes:
      - ../:/app
      - /app/node_modules
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - acamae-network

networks:
  acamae-network:
    external: true

volumes:
  node_modules:
