services:
  frontend:
    build:
      context: ../
    container_name: acamae-frontend
    stdin_open: true
    tty: true
    env_file:
      - ../.env.development
    expose:
      - '3000'
    volumes:
      - ../:/app
      - /app/node_modules
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - acamae-network

  nginx:
    build:
      context: ./nginx
    container_name: acamae-nginx
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      frontend:
        condition: service_healthy
    networks:
      - acamae-network

networks:
  acamae-network:
    driver: bridge

volumes:
  node_modules:
