name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    environment: development
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install GNU coreutils (for sha256sum)
        if: runner.os == 'macOS'
        run: brew install coreutils
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
      - run: node scripts/validate-critical-config.js
      - run: node scripts/validate-workflows.js

  lint:
    needs: validate
    runs-on: ${{ matrix.os }}
    environment: development
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install GNU coreutils (for sha256sum)
        if: runner.os == 'macOS'
        run: brew install coreutils
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
      - run: npm run lint:fix
      - run: npm run lint

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    environment: development
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install GNU coreutils (for sha256sum)
        if: runner.os == 'macOS'
        run: brew install coreutils
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
      - run: npm run build
      - run: npm run test:coverage
      - run: npm run check:coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
