name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ${{ matrix.os }}
    environment: development
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install GNU coreutils (for sha256sum)
        if: runner.os == 'macOS'
        run: brew install coreutils
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
      pull-requests: read

  validate:
    needs: prepare
    runs-on: ${{ matrix.os }}
    environment: development
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
      - run: node scripts/validate-critical-config.js
      - run: node scripts/validate-workflows.js
    permissions:
      contents: read
      packages: read
      pull-requests: read

  lint:
    needs: validate
    runs-on: ${{ matrix.os }}
    environment: development
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
      - run: npm run lint:fix
      - run: npm run lint
    permissions:
      contents: read
      packages: read
      pull-requests: read

  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    environment: development
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
      - run: npm run build
      - run: npm run test:coverage
      - run: npm run check:coverage
    permissions:
      contents: read
      packages: read
      pull-requests: read

  sonarqube:
    needs: test
    name: SonarQube
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22]
    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: read
      packages: read
      pull-requests: read
