name: CI

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write # Para poder comentar en PRs si hay fallos

    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Run linter with --fix
        run: npm run lint:fix

      - name: Run linter (fail on remaining errors)
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run tests with coverage
        run: |
          npm run test:coverage
          ls -la coverage/

      - name: Check coverage thresholds
        run: npm run check:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: ./coverage
          retention-days: 7

  version:
    needs: build-lint-test
    if: ${{ github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/')) }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}
          setup-git-identity: 'true'

      - name: Version and tag
        run: |
          # Extraer el tipo de rama (feature o fix)
          BRANCH_TYPE=$(echo ${{ github.ref }} | sed -n 's/refs\/heads\/\(feature\|fix\)\/.*/\1/p')

          # Generar versión prerelease
          npx lerna version --no-push --preid=${BRANCH_TYPE} --pre-dist-tag ${BRANCH_TYPE}

          # Pushear cambios y tags
          git push --follow-tags

