name: Lighthouse

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    environment: development
    timeout-minutes: 15
    permissions:
      contents: read
      packages: read
      pull-requests: write # In order to comment in PRs if there are errors
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          npm-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build

      - name: Start local server
        id: server
        run: |
          npx serve dist -s &
          echo "server_pid=$!" >> $GITHUB_OUTPUT
          echo "Waiting for server to be ready..."
          timeout 30s bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 1; done' || (echo "Server failed to start" && exit 1)

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Upload Lighthouse report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci
          retention-days: 7

      - name: Stop local server
        if: always() && steps.server.outputs.server_pid
        run: kill ${{ steps.server.outputs.server_pid }} || true

      - name: Notify on performance regression
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '📉 Regression detected',
              body: `A performance regression has been detected in the commit ${context.sha}.\n\nPlease review the Lighthouse report for more details.`,
              labels: ['performance', 'regression']
            });
