name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@emanager.com'

      # Install build and test dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Build
        run: npm run build
        working-directory: ./

      - name: Test
        run: npm test
        working-directory: ./

      # TODO: Add publish with Lerna
      # - name: Lerna publish
      #   run: npx lerna publish from-package --yes
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
